services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  solicitud:
    build: ./solicitudes
    container_name: solicitudes
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  procesamiento:
    build: ./procesamiento
    container_name: procesamiento
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
  
  notificacion:
    build: ./notificacion
    container_name: notificacion
    ports:
      - "5001:5001"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  
